### ISSUE TITLE
2nd intl. day of research software, Oct 13th 2022

### ISSUE THREAD

**Issue by StephanJanosch** [DE-RSE/projekte#11]

**Comment by StephanJanosch** [comment]
all online

rough idea by myself

- 10.00 am: Welcome, 
-  What and why? What is so special about research software?
-  short News from MPG, HGF, Fraunhofer
- 10.15 am AG RSE , NFDI Common Infra 
  - infrastructure needed for mature projects
    - proxy entity to ask funding to develop a new feature
    - maintainer for mature research software - not a project anymore
    - community manager for very mature research infrastructure software 
- 10.45 https://www.nfdi.de/section-edutrain/ ?
- 11.15. What are the carpentries?
- discussion
- 12.30 am lunch
- ~~13.30 report Allianz AG workshop~~ not appropriate
- 14.00 what happens in Austria and Swiss? 
   - do you know somebody? Via EOSC? 
- 14.30 maybe a Carpentries instructor community call. Spoke with DACH coordinator (education)

**Comment by StephanJanosch** [comment]
Ich fühle mich beobachtet @konrad

**Comment by konrad** [comment]
Dein Gefühl stimmt, @StephanJanosch. :grimacing:

**Comment by HeidiSeibold** [comment]
@StephanJanosch you asked if we knew anyone interested in RSE from 🇨🇭 or 🇦🇹. Here a few people I think might be interested (not an exhaustive list, I could probably come up with way more…):

@dhugpeter 🇨🇭 
@mbannert 🇨🇭 
@danielinteractive 🇨🇭 
@rachelHey 🇨🇭 
@krlmlr 🇨🇭 
@freezenik 🇦🇹 

Would any of you be interested in saying something about the state of research software engineering in 🇦🇹 or 🇨🇭 ?

**Comment by danielinteractive** [comment]
Thanks @HeidiSeibold for tagging me - sure I would be happy to contribute

**Comment by mbannert** [comment]
Thanks @HeidiSeibold, I am honored to make that non-exhaustive list. Definitely interested to contribute / attend. Please let me know how I can help.

**Comment by rachelHey** [comment]
Thank you @HeidiSeibold for thinking of me. :) I am super interested in the topic, but I am unfortunately not up-to-date regarding the latest developments in CH. We are still fighting to get the term "reproducibility" on different road-maps here in CH. I can imagine that RSE-topics might be even harder to address with stakeholders....
(I however plan to ask for funding for an RSE in a research proposal, so I might come back to some of you if I get the funding and I can actually hire one).

**Comment by pancetta** [comment]
Hey @StephanJanosch, I like the idea of short updates from the major research associations. For HGF I could think of [HIFIS](https://www.hifis.net/) (anyone?), [HiRSE_PS](https://www.helmholtz-hirse.de/) and a short 'hello' from [Claire Wyatt](https://www.software.ac.uk/about/staff/person/claire-wyatt), just arriving at FZJ to support RSE at FZJ, HGF and DE.

**Comment by krlmlr** [comment]
Thanks, I'm a bit out of touch with research software and RSE these days.

**Comment by nuest** [comment]
Tagging a couple of people from :switzerland: that were interested in RSEng:

@chenkins
@moritz9

**Comment by ineiti** [comment]
Crashing the party - I discussed with Matthew Baker and Uwe Schmitt from the ETHZ during the RSECon22 and we're looking to start a CHapter of the RSE movement directly in🇨🇭. We now have a #switzerland channel on the [UKRSE-slack](https://docs.google.com/forms/d/e/1FAIpQLSdqs-_QNwQFzCIUEafah91E5E00lGUEnTPC4jjYbGUqPjONwA/viewform).

So all of the tagged 🇨🇭 RSEs are very welcome to join us there!

**Comment by StephanJanosch** [comment]
möglicher Verbreitungsweg für den Event: https://www.oana.at
https://www.zeileis.org/
https://forschungsdaten.info/fdm-im-deutschsprachigen-raum/oesterreich/
https://www.jku.at/bibliothek/kontakt/team/team-bibliometrie/

**Comment by StephanJanosch** [comment]
@konrad 
Kannst du mal bitte in der NFDI-Sektion EduTrain (https://www.nfdi.de/section-edutrain/) nachfragen, ob jemand Zeit hätte diese vorzustellen? Da spare ich mir den Weg über den Sprecher.

Vielen Dank!

**Comment by konrad** [comment]
> @konrad Kannst du mal bitte in der NFDI-Sektion EduTrain (https://www.nfdi.de/section-edutrain/) nachfragen, ob jemand Zeit hätte diese vorzustellen? Da spare ich mir den Weg über den Sprecher.
> 
> Vielen Dank!

Ja, mache ich.

**Comment by Sideboard** [comment]
What's the current state? Will it take place?

**Comment by StephanJanosch** [comment]
I have time this afternoon to organise further. Working alone on it, takes time. And I can't work faster.

**Comment by StephanJanosch** [comment]
Hi All,

the event has been announced. We have a pad. https://pad.gwdg.de/44b79pTvSYae9QEr8c5Dhw?view

Please help be filling the pad with more concrete names and or short contributions. I know it's super later. But not too late

**Comment by StephanJanosch** [comment]
> What's the current state? Will it take place?

Yes, now it's out. The Event will take place

**Comment by danielinteractive** [comment]
@StephanJanosch I could give a 10 mins update what is going on in the Pharma space (yes there is RSE too :-), e.g. at 2 pm (CH)?

**Comment by HeidiSeibold** [comment]
@danielinteractive @mbannert et al from Switzerland + Austria. Will you be able to join at 2 to give a short informal update? 

See agenda and login link here: https://pad.gwdg.de/44b79pTvSYae9QEr8c5Dhw?both

**Comment by HeidiSeibold** [comment]
A sorry Daniel, I just missed that you already said you could 😅

**Comment by danielinteractive** [comment]
@HeidiSeibold no worries, thanks for the reminder! I almost forgot it :D

**Comment by StephanJanosch** [comment]
Thanks @HeidiSeibold !

**Comment by StephanJanosch** [comment]
> @StephanJanosch I could give a 10 mins update what is going on in the Pharma space (yes there is RSE too :-), e.g. at 2 pm (CH)?

Please do @danielinteractive . If there is a lot of input from CH and A then I need to to reduce your time slot to 5 mins. But yes sure!

**Comment by StephanJanosch** [comment]
Hi dear
@mbannert 
@dhugpeter
@rachelHey 
@freezenik
@chenkins
@moritz9
@ineiti

Maybe some of you find some time to join TODAY at 2pm CEST our video call for 2nd international research software engineer. call.

Agenda: https://pad.gwdg.de/44b79pTvSYae9QEr8c5Dhw?view
Call URL: https://meet.gwdg.de/b/ste-hku-nvu
Time and Date: Today, 2pm CEST

Thank you!

**Comment by mbannert** [comment]
I had it blocked in my agenda, but can't make it. I had to postpone teaching todag because of illness. Sorry everyone!

**Comment by StephanJanosch** [comment]
Thanks for letting us know @mbannert . Thank you for the effort!

**Comment by mbannert** [comment]
Would be nice to have a quick update. Recording link in case this exists would also be very nice.

**Comment by konrad** [comment]
Many thanks to everybody who contributed to this great event today. Special thanks to @StephanJanosch for the organization! You :rock:!

**Comment by StephanJanosch** [comment]
Thanks everybody! Especially @HeidiSeibold .

**Comment by HeidiSeibold** [comment]
Well, thank YOU @StephanJanosch 👏 
What a wonderful international RSE day 🎉
