### ISSUE TITLE
communication wg

### ISSUE THREAD

**Issue by StephanJanosch** [DE-RSE/projekte#13]
Email: liste@de-rse.org
Twitter: http://twitter.com/rse_de
mastodon: https://mastodon.social/@de_rse

**Comment by StephanJanosch** [comment]
Twitter account email has been moved over to Vorstand from @sdruskat.

**Comment by StephanJanosch** [comment]
Mastodon liegt imho bei C.Busse

**Comment by StephanJanosch** [comment]
Email Christian Busse - wie soll es mit https://mastodon.social/@de_rse weiter gehen?

**Comment by caha42** [comment]
@StephanJanosch hat sich hier was ergeben? Haben wir Zugriff auf den Mastodon Account?

**Comment by StephanJanosch** [comment]
Email nochmal an Christian versand
