### ISSUE TITLE
Infrastuktur-AG

### ISSUE THREAD

**Issue by StephanJanosch** [DE-RSE/projekte#15]

**Comment by fiveop** [comment]
Ich bin interessiert

**Comment by StephanJanosch** [comment]
mention: @Chilipp

**Comment by Chilipp** [comment]
Thought we name it _Arbeitskreis_? :sweat_smile:

**Comment by StephanJanosch** [comment]
Ja, doch. 🙃 Ich wollte nur fix einen Ort schaffen, wo man anknüpfen kann. Bevor es wieder wegläuft. Ich hab gerade viel zu tun. Einstweilen schlage ich vor, diesen Ort für irgendwas zu nutzen. Nächste Vorstandssitzung ist gerade in Terminfindung.

**Comment by StephanJanosch** [comment]
Open Slides: Jan Phillip Thiele

**Comment by Chilipp** [comment]
hey everyone and a happy new year!! time to get this started :smiley: :tada: @jpthiele @fiveop do you think we can arrange a meeting here? We need to formerly create this *Arbeitskreis* and elect a representative for the Sprecherrat and discuss some things about the infrastructure that we (want to) have. @ClaireWyatt and @caha42 maybe you want to join this discussion as you made a poll on the communication platform for deRSE last year? I'd be happy to setup a poll for a meeting, but before I do that, you have 24h to make any comments on possible dates (otherwise I will aim for the last week of January)

**Comment by ClaireWyatt** [comment]
Hi Philipp, Happy New Year! Last week of January is better for me yes.

**Comment by fiveop** [comment]
For the last week of January my calendar is fairly empty as well.

**Comment by Chilipp** [comment]
hey @ClaireWyatt @fiveop @jpthiele, thanks for the feedback! Please enter your available dates until Thursday evening (January 11th) here: https://terminplaner6.dfn.de/p/134eac7ba2e7bce279c820ce112df4cf-539551

**Comment by caha42** [comment]
Sorry, I am not available on all of the proposed dates. But I am also not sure if I wanna join. I do not really want to take care of infrastructure, I am "just" fine with moderating the online community. :)

**Comment by fiveop** [comment]
I submitted the form, but did not get any feedback whether it succeeded. Did I vote?

**Comment by Chilipp** [comment]
great! thanks for the fast response!

> I submitted the form, but did not get any feedback whether it succeeded. Did I vote?

yes you did. but because I put the link to the poll in a public issue, I made the responses hidden for the purpose of privacy :sweat_smile:

**Comment by Chilipp** [comment]
@caha42 

> I do not really want to take care of infrastructure, I am "just" fine with moderating the online community. :)

I totally understand that you do not want to take care of the infrastructure, but you may have an opinion on the software we use on that infrastructure. the decision about what we offer/use as platforms for the community is also part of the discussion in this AK

**Comment by Chilipp** [comment]
I sent you the meeting information via mail. please let me know if you did not receive them

**Comment by StephanJanosch** [comment]
sorry for being inactive. I am super busy. 

If I could leave a wish: Don't forget to evaluate OpenSlides as tool for handling many working groups with issues in an organisation..

**Comment by StephanJanosch** [comment]
https://infra.run/ als host für (Teile) unserer Infrastruktur? 

originalIdee von Daniel Nuest

**Comment by caha42** [comment]
Hehe - infra.run is run by a friend of mine, who started it to run infrastructure for schools since he was annoyed with the situation and did not want all of them to end up with proprietary software.

**Comment by Chilipp** [comment]
moin! klinkt interessant, schaue ich mir an. Ich hätte für einen VPS auf windcloud.de mit cloudron als Betriebssystem plädiert.

https://windcloud.de/produkte/vps/
https://www.cloudron.io/

auf windcloud steht gerade bei den VPS *Out-of-Stock*, aber ich habe interessehalber nachgefragt und man kann sie weiterhin bestellen. diese setup nutze ich als privater Server und bin damit sehr zufrieden, es ist hochverfügbar und schnell. und auch recht preisgünstig (für einen VPS L mit 4 vCPU, 12 GB RAM und 500GB Festplattenspeicher) zahlt man inkl. Cloudron-Subscription ca. 32€ im Monat. cloudron bietet eine [große Menge an einfach zu installierenden und zu administrierenden apps inkl. Single-Sign-On und Email-Server](https://www.cloudron.io/store/index.html)

aber das können wir ja bei oder nach dem Treffen evaluieren

**Comment by Chilipp** [comment]
moin! 

just to keep the reference, we will continue the discussion in an issue to the [`infrastructure` repo](https://github.com/DE-RSE/infrastructure). We will then present our plan to the society.

> If I could leave a wish: Don't forget to evaluate OpenSlides as tool for handling many working groups with issues in an organisation..

@StephanJanosch I am afraid that so far it does not look very promising for open slides. According to jpthiele, the deployment is quite some effort and it is not clear, whether we can guarantee this in a sustainable manner. The [Community Portal that is developed in my team](https://codebase.helmholtz.cloud/hcdc/django/clm-community/django-academic-community/) may be an alternative and works with the above-mentioned cloudron-solution, but some of the features (e.g. the polls would need to be implemented (which is possible, though)).
