### ISSUE TITLE
1. deutsches RSE-Gruppentreffen 2021

### ISSUE THREAD

**Issue by knarrff** [DE-RSE/projekte#2]
![](https://de-rse.org/assets/img/site/rse.png)
# 1. deutsches RSE-Gruppentreffen 2021

Es gibt in Deutschland nicht nur viele einzelne RSE, sondern schon einige **[RSE-Gruppen](https://pad.gwdg.de/M0F4dmG9SoiEaORnZr-jmg)** und man hat fast das Gefühl, es werden wöchentlich mehr. Allerdings gibt es bisher **kaum Kontakt** zwischen ihnen. Wir wollen das **ändern**.

Innerhalb der nächsten 2-3 Monate soll es ein (leider immer noch nur virtuelles) Treffen von Vertretern dieser RSE-Gruppen geben.

Wie dieses Treffen genau aufgebaut sein wird, über welche Themen wir sprechen werden und wann bzw. wie lange wir uns treffen, ist mit Absicht jetzt noch nicht festgelegt, denn dazu hätten wir **euch**, die Mitglieder von RSE-Gruppen in Deutschland gern **an Bord**.

Wenn ihr Interesse habt, an der Gestaltung und Organisation des Treffens von Anfang an mitzuwirken, dann:
1. hinterlasst hier einen Kommentar (so können wir euch leicht erreichen) **und**
2. Tragt eure Verfügbarkeit in der Woche vom 26.-30.4. ein: https://terminplaner4.dfn.de/EsijxDRnawGyCanH

(Das ist keine Teilnehmendenliste: die wird später kommen.)

Um den Stein vielleicht ins Rollen zu bekommen, schlage ich vor:

1. [x] Ticket als Mitmachaufruf erstellen
2. [x] Zeitumfrage Orgatreffen
3. [x] Plan bewerben: 1 Woche Mitmachaufrufphase (bis 23.4.)
4. [x] virtuelles Orgatreffen: 28. 4. 2021 13 Uhr: https://meet.gwdg.de/b/ste-hku-nvu
    - [x] groben Zeitraum festlegen: danach Zeitumfrage Gruppentreffen
    - [x] grobe Infrastruktur festlegen (Konf.-system, andere Kanäle)
    - [x] Inhaltsform festlegen
    - [x] Umfrage nach Inhalten, evtl. per Einreichung von Ideen + Abstimmung für die Ideen
    - [ ] Aufgaben Personen zuordnen
5. [x] noch auszuarbeiten: Gruppentreffen im Zeitraum Mai/Juni?

**Comment by tscheypidi** [comment]
schöne Initiative, bin dabei.

**Comment by caha42** [comment]
Find ich gut. Wichtig wäre allerdings zu wissen wie lange das Meeting gehen soll um sich sinnvoll in die Umfrage eintragen zu können. :)

**Comment by knarrff** [comment]
Ich ging von einer Stunde aus. Wir müssen da ja nicht gleich alles klären.

**Comment by JR-1991** [comment]
Finde ich sehr gut! Bin gerne dabei

**Comment by uekerman** [comment]
An der Universität Stuttgart arbeiten wir auch gerade an einer zentralen RSE Gruppe. Wir kommen zum Treffen und bringen uns auch gerne bei der Orga mit ein.

**Comment by knarrff** [comment]
Pad für Agenda des 1. Treffens: https://pad.gwdg.de/H1q-1eOaS5eRW36_Jqr97g?both

**Comment by sdruskat** [comment]
Zur Inhaltsform (s. Pad): Mein ursprünglicher Vorschlag für dieses Treffen hätte in etwa initial Kurzvorträge (in Lightning Talk-Länge) nach fester Form als Steckbrief der jeweiligen Gruppen vorgesehen, dann Pitches für und Durchführung von Breakout-Gruppen und Berichterstattung in Plenum, alternativ World Café. Dazu Diskussion und Planung der folgenden Vernetzungstreffen. 

In UK werden diese Treffen ("Leaders Meetings") regelmäßig abgehalten, derzeit so weit ich weiß im Quartalsturnus.

**Comment by knarrff** [comment]
Chaträume:
- [x] https://chat.gwdg.de/group/derse_gruppenleitungstreffen-orga
- [x] https://chat.gwdg.de/group/derse_gruppenleitung

**Comment by knarrff** [comment]
Wir haben nun einen RocketChat-Raum für Sachen, die die Organisation betreffen: https://chat.gwdg.de/group/derse_gruppenleitungstreffen-orga. Wie besprochen ist das ein geschlossener Raum, aber jede/r der möchte, kann eingeladen werden. Ich habe die Teilnehmenden vom letzten Treffen schon dazugefügt, falls 1. das System sie schon kannte und 2. der Name eindeutig aufgelöst werden konnte. Wer noch nicht Mitglied ist, es aber gern sein möchte: bitte erst beim System selbst anmelden (am besten per https://chat.gwdg.de/channel/derse) und dann bei mir melden (und falls Vorname-Nachname-Dopplungen bekannt sind, gleich mit dem richtigem "username").

Gleich hier (weil evtl. nicht alle im #derse Kanal sind: ich muss leider das 2. Treffen zeitlich etwas verschieben: https://terminplaner4.dfn.de/hkwAzYZDoaLcBTiy

**Comment by knarrff** [comment]
Ich habe bis zuletzt auf einen Favoriten gehofft. Da nun aber alle Optionen gleich besetzt sind, muss der Mittagsmalus entscheiden (sorry: einen Jan trifft es immer): Wir treffen uns 14 Uhr hier: https://meet.gwdg.de/b/ste-hku-nvu

**Comment by JR-1991** [comment]
Leider kann ich um 14 Uhr nicht teilnehmen, da ich in einem Workshop bin. Daher lege ich die Umfrage-Tools, welche ich für das RSE-Treffen herausgesucht habe, hier ab:

- [Slido](https://www.sli.do/de) - Sehr etabliert und bietet eine umfangreiches Arsenal an Q&A/Poll-Features.
- [Poll for all](https://www.pollforall.com/en/index.html) - Simple UI und for free.
- [Vevox](https://www.vevox.com/) - Umfangreich und bietet zudem eine nahtlose Powerpoint-Integration.
- [Direct Poll](https://directpoll.com/) - Sehr simpel, aber gets-the-job-done und ist for free.

Wünsche euch ein produktives Meeting und einen angenehmen Mittwoch!

**Comment by ajaust** [comment]
Ich habe die Diskussion bzgl. der neuen Uhrzeit auch verpasst und kann um 14 Uhr leider ebenfalls nicht. Im Protokoll vom letzten Mal habe ich mich aber noch als Freiwilliger für das Protokoll bzw. Blogpost eingetragen.

**Comment by knarrff** [comment]
Ok - da nun doch so viele 14:00 nicht können, lasst uns 13:30 probieren. Das könnte bei gutem Verkehr hier passen.

**Comment by knarrff** [comment]
Agenda für heute (bitte gern ergänzen): https://pad.gwdg.de/zkcGGSarStSPvgJL6J8Qjg

**Comment by tscheypidi** [comment]
Hier ist eine Folie zu unserer RSE-Gruppe am PIK von Lavnia und mir für die Kurzvorstellung: [RSEfTP_lightning.pdf](https://github.com/DE-RSE/projekte/files/6708185/RSEfTP_lightning.pdf)

**Comment by berndflemisch** [comment]
Ich freue mich schon auf das Treffen morgen und darauf, unsere RSE-Anstrengungen in Stuttgart vorzustellen: 
[stuttgart_rse.pdf](https://github.com/DE-RSE/projekte/files/6710388/stuttgart_rse.pdf)

**Comment by dokempf** [comment]
Hier auch ein paar Folien zum Scientific Software Center an der Uni Heidelberg: 
[ssc_derse.pdf](https://github.com/DE-RSE/projekte/files/6711328/ssc_derse.pdf)

**Comment by llamm-de** [comment]
Ich freue mich auch darauf mich mit euch austauschen zu dürfen. Hier sind meine Folien: [deRSE_Aachen_chapterMeeting_2021.pdf](https://github.com/RSE-Aachen/Presentations/blob/main/25_06_2021-Chapter%20Meeting/deRSE_chapterMeeting_2021.pdf)

**Comment by CaptainSifff** [comment]
Auch hier zwei  Folien zu Würzburg.
[rse-intro.pdf](https://github.com/DE-RSE/projekte/files/6712826/rse-intro.pdf)

**Comment by knarrff** [comment]
[zedif.pdf](https://github.com/DE-RSE/projekte/files/6714087/zedif.pdf)

**Comment by jlinx** [comment]
Hier auch noch 2 Folien aus Braunschweig
[RSE_TU_Braunscheig.pdf](https://github.com/DE-RSE/projekte/files/6714088/RSE_TU_Braunscheig.pdf)

**Comment by Chilipp** [comment]
moin! und hier noch vom [Helmholtz Coastal Data Center (HCDC) vom Helmholtz-Zentrum Hereon aus Geesthacht](https://nubes.helmholtz-berlin.de/s/CwAQwAGXzefTqSJ).

**Comment by wm75** [comment]
Von mir stellvetretend für die Bioinformatik der Uni Freiburg und speziell für das Team hinter dem europäischen Galaxy-Server (https://usegalaxy.eu): https://usegalaxy-eu.github.io/freiburg/services

**Comment by StephanJanosch** [comment]
Slides vom MPI-CBG
[MPI-CBG_Dresden.pdf](https://github.com/DE-RSE/projekte/files/6714295/MPI-CBG_Dresden.pdf)

**Comment by jlinx** [comment]
Nochmal eine neue Version
[RSE_TU_Braunscheig.pdf](https://github.com/DE-RSE/projekte/files/6714338/RSE_TU_Braunscheig.pdf)
