### ISSUE TITLE
Internationaler RSE Tag 14.10.2021

### ISSUE THREAD

**Issue by StephanJanosch** [DE-RSE/projekte#4]
* voraussichtlich 14.10.2021 
* als Ersatz für nationale RSE Conference
- [x] Bestätigung des Councils

https://github.com/DE-RSE/projekte/projects/1
pad: https://cryptpad.fr/code/#/2/code/edit/rIspK5eXBJH21l4KbhRcDUc6/

**Comment by StephanJanosch** [comment]
Ich plane einen MPG-RSE-Call durchzuführen. Ich denke wir brauchen einen Zeitslot für "interne Calls", den Organisationen für sich nutzen können, ohne mit anderen Community-Calls zu kollidieren. Daher schlage ich ein grobe Terminplanung für den Tag vor

10-12 lifecycle specific topics
13-14 RSE role, careers
14.30-16 opportunity for self hosted calls

danach könnte man was internationales dran hängen @sdruskat

**Comment by sdruskat** [comment]
> danach könnte man was internationales dran hängen @sdruskat

Oder man macht den Teil von 10-12 & 13-14 international, so könnten zumindest :eu: RSEs teilnehmen (Sprache wäre dann allerdings natürlich Englisch). Das verhinderte allerdings auch inhaltliche Dopplungen ... 

Oder man macht zwei Runden, eine _de_, dann self hosted calls, dann _en_. Wer doppelt "vortragen" möchte ist herzlich eingeladen, ansonsten stelle ich mir tatsöchlich eher eine ad hoc Veranstaltung vor.

**Comment by StephanJanosch** [comment]
Ich hab gerade keine Kraft international zu koordinieren. Daher hätte ich die kleine Variante bevorzugt. Ich hab vor Schreck sogar den Kanal vergessen, auf dem man int. Slots abstimmen könnte.

**Comment by sdruskat** [comment]
> Ich hab gerade keine Kraft international zu koordinieren. Daher hätte ich die kleine Variante bevorzugt. Ich hab vor Schreck sogar den Kanal vergessen, auf dem man int. Slots abstimmen könnte.

Würde das gar nicht groß koordinieren. Würde einfach den Kanal anbieten und wer Lust und Muße hat kommt dann zum englischsprachigen Slot dazu. *Sehr* lockeres Setup.

**Comment by StephanJanosch** [comment]
Und wo bringst du einen deutschsprachigen Slot unter? Würde ich gerne sehen, um eine Barriere weniger für manche zu haben

**Comment by sdruskat** [comment]
Gute Frage, vielleicht sollten wir das einfach ausschließlich deutschsprachig machen. Wer Internationales will kann ja zu anderen Veranstaltungen gehen.
Vielleicht kann man auch einfach eine gemeinsame internationale Runde ganz am Ende machen,
Ich hab da mal was vorbereitet: https://pad.gwdg.de/Av2TjfsxQme4qWXQSA8hCw?both

Subthemen des Zyklus müssen noch ausgearbeitet werden, Links für Call und Pads können einfach in die Agenda geklatscht werden. Fertig.

**Comment by sdruskat** [comment]
Habe gerade überlegt: an meiner Inst. gibt es vielleicht ne größere Gather Town-Lizenz, da könnte man dann Sessions auch parallelisieren :thinking:. Soll ich mal fragen?

**Comment by sdruskat** [comment]
Re internationale Session: Können ja beim nächsten Council Meeting mal schauen, ob wir da ne Zeit abstimmen können, wo sich alle mal für ne Stunde zusammenklicken können um den Tag aus den einzelnen Events Revue passieren lassen zu können.
/cc @knarrff

**Comment by StephanJanosch** [comment]
Das hast du gut vorbereitet @sdruskat ! Tolles pad. Ich habe das Thema im Community-Talk heute auch angebracht und hierher verwiesen. @Konrad würde da auch gern beisteuern. @BFrit hat auch gesagt, dass dieses Event sich irgendwie auch in die NFDI herumgesprochen hat. Daher wäre ein Slot "Software in NFDI" sicherlich nötig.

**Comment by StephanJanosch** [comment]
- [x] Ich baue mal einen BBB-Raum bei der GWDG dafür

**Comment by StephanJanosch** [comment]
Es fehlt noch 2 Aspekte im Programm

- [x] Nachnutzung 
- [x] Workflows

ich bastel da nochmal dran drum

**Comment by StephanJanosch** [comment]
Ich baue Slides mit den passenden Fragen um das Publikum einzufangen

**Comment by StephanJanosch** [comment]
Slides: nicht fertig, aber immerhin
[welcome and structure slides.pdf](https://github.com/DE-RSE/projekte/files/7338879/welcome.and.structure.slides.pdf)

**Comment by konrad** [comment]
Danke für die Organisation - ich habe es den Event auf der generellen NFDI-Mailingliste und im NFDI-Rocket-Chat beworben und bin morgen beim NFDI-Slot gerne mit dabei.

**Comment by StephanJanosch** [comment]
Feedback: Mittagspause sollte als echte Pause dienen. remote community lunch hat nicht funktioniert
Alles fein sonst. Format hat ausgezeichnet funktioniert
