### ISSUE TITLE
invitation to WoSSS21

### ISSUE THREAD

**Issue by StephanJanosch** [DE-RSE/projekte#5]
- https://wosss.org/wosss21-home/
 - board discusses issue July 27th

**Comment by axel-loewe** [comment]
Ich denke Peter hat Bezug auf das Positionspapier genommen, das Gunnar und ich damals initiiert und gemeinsam mit Hartwig, Felix, Stephan, Frank, Bernhard und Alexander organisiert haben. Dort sind Gunnar und ich als Corresponding Authors genannt, ich denke im de-RSE Vorstand ist das Thema aber mindestens so gut platziert.

https://doi.org/10.12688/f1000research.23224.2
https://arxiv.org/abs/2005.01469

**Comment by StephanJanosch** [comment]
Das macht Sinn, da ich nur am Rande involviert war, hab ich das nicht vollumfänglich auf dem Schirm gehabt.

**Comment by StephanJanosch** [comment]
@astruck hat sich bereit erklärt das zu übernehmen. Er braucht Slides

- [x] slides

**Comment by StephanJanosch** [comment]
@sdruskat ist auch involviert

**Comment by StephanJanosch** [comment]
@astruck, ich nehme an dieses Ticket kann geschlossen werden. Willst du eventuell noch 3 Worte im nächsten Vorstandcall loswerden? Ich meine, wir haben dir ja da echt zu danken!

**Comment by knarrff** [comment]
- [ ] @BFrit  wird @astruck in Person treffen und ihn fragen, ob er uns berichten kann.
