### ISSUE TITLE
A template for the perfect RSE group at a german university

### ISSUE THREAD

**Issue by CaptainSifff** [DE-RSE/projekte#6]
Ausgehend vom letzten RSE-Gruppenleiter Treffen,
haben diejenigen, die noch keine RSE Gruppe haben, so etwas an ihrer Einrichtung aber extrem sinnvoll finden
den Vorschlag gemacht Ideen zu sammeln, wie so eine Gruppe aussehen könnte.
Unsere Ideen sammeln wir hier:
https://pad.gwdg.de/6tzCj8ndSYa2JYda683BOw?view#

Natürlich hat jede Universität eine andere Ausgangssituation, aber das template sollte dann genügend Bausteine bieten,
die dann an die lokale Situation adaptiert werden können.
Leute die bereits RSE-Gruppen haben, dürfen sich auch gerne angesprochen fühlen. Wir wollen nicht schon in der Antragsphase Fehler wiederholen 🙂
Wir möchten auch ein paar Geschichten sammeln, was bereits funktioniert/nicht funktioniert hat.

**Comment by CaptainSifff** [comment]
Man kann natürlich auch darüber nachdenken die Evaluation der Gruppe hier mit zu diskutieren.

**Comment by StephanJanosch** [comment]
Muss man zwischen Universität und einer außeruniversitären Forschungseinrichtung unterscheiden? Wenn ja, würde ich in dem Template wo angebracht eine Notiz machen.

**Comment by knarrff** [comment]
Dafür wird es ein Positionspapier geben: ist in Arbeit.
