### ISSUE TITLE
Jahresausklangstreffen 2021

### ISSUE THREAD

**Issue by knarrff** [DE-RSE/projekte#8]
Es wäre schön, dieses Jahr noch einmal ungezwungen zusammenzukommen und ganz (oder zumindest fast) ohne Agenda über RSEs und die Welt zu reden und vielleicht sogar mit vorbereiteten Spielen/Aktivitäten zusammen Spaß zu haben. Dazu sollen hier erst einmal Ideen gesammelt werden.

**Comment by knarrff** [comment]
Wir brauchen:
- [ ] Umfrage, wann es Leuten eher passt (sowohl Datum als auch "während der Arbeitszeit" oder eher "abends ab 8 und open end")
- [x] Virtueller Raum: https://meet.gwdg.de/b/ste-hku-nvu . Kann sich aber gern noch woanders hin ändern, wenn man dort dann besser "abhängen" kann, e.g., gather.town falls das jemand vorbereiten kann/mag.
- [ ] eventuell: virtuelle Aktivitäten für >(?) 10 Personen
    - evtl.: collaboratives Programmieren einer kleinen Aufgabe
        - evtl. mit JupyterLab mit angeschaltenem collabortivem Editieren (hat da jemand Erfahrungen/Server?)

**Comment by jlinx** [comment]
Ich könnte Spot anbieten als Ort zum Treffen.
https://www.spotvirtual.com/

**Comment by CaptainSifff** [comment]
Lan-Party! Haben wir eine Steam-Gruppe?

**Comment by StephanJanosch** [comment]
@knarrff close?
