### ISSUE TITLE
un-deRSE23 - deRSE Workshop 2023

### ISSUE THREAD

**Issue by StephanJanosch** [DE-RSE/projekte#9]
- Nach o. vor den Sommerferien
 - über 2 oder 3 Abende
 - Imbiss und Getränke tagsüber
 - hybrid
 - Mitgliederversammlung
 - Unkonferenz-Style
 - Gästehaus wäre nett
 - bar camp-style
 - local organiser
 
## Orte

* Jena?
  * MPI, Zeiss
* Telegrafenberg    
## Zweck

* Reflektieren
* neu ausrichten
*

**Comment by florianthiery** [comment]
spontane Fragen / Ideen

- Adressantenkreis: Vereinsmitglieder, Core-Community, RSEs in Deutscland?
- wenn Mitgliederversammlung mind. für Anzahl Vereinsmitglieder planen ~50
- ggf. ein Tag mit Barcamp/Unconf danach MV, Tag davor und danch eher Community / Vorstands Sessions?

**Comment by StephanJanosch** [comment]
## Vor der Klausur

* VIGO-Auschreibung der DFG für Community-Manager prüfen (hat u.a. @tscheypidi gemacht) 

## Ziel der Klausur

Wege finden, um den Verein als handelnde Entität zu mehr Leben zu verhelfen.

* Rolle eines Community-Managers definieren
  * Antrag für Community-Manager fertigstellen
  *  Bearbeitung öffentlicher durch Community-Manager sicherstellen
* Fellowship-Programm
* NFDI-Beteiligung
  * Auf welche Weise nimmt wer wie teil?   
* Vereinsinfrastruktur
  * Mailingliste (spam)
  * Webseite
* Mitgliederversammlung vorbereiten
   * Satzungsänderungen einsammeln
   * Vorstand rotieren?

**Comment by StephanJanosch** [comment]
Ich habe den Titel geändert. Verlegt nach 2023 ;-)
